export  const schedule = {
    'SEGUNDA-FEIRA': [
      {
        startTime: '08:00',
        endTime: '08:30',
        title: 'APRESENTAÇÃO HACKATHON',
        subtitle: '',
      },
      {
        startTime: '08:30',
        endTime: '20:00',
        title: 'HACKATHON TRACTIAN',
        extend: true,
        subtitle: '',
      },
    ],
    'TERÇA-FEIRA': [
      {
        startTime: '13:00',
        endTime: '13:45',
        title: 'CREDENCIAMENTO',
        subtitle: '',
      },
      {
        startTime: '13:45',
        endTime: '14:30',
        title: 'ABERTURA',
        subtitle: '',
      },
      {
        startTime: '14:30',
        endTime: '15:30',
        title: 'Python 4ever:',
        subtitle: 'o poder dos geradores',
      },
      {
        startTime: '15:30',
        endTime: '16:00',
        title: 'COFFEE BREAK',
        subtitle: '',
      },
      {
        startTime: '16:00',
        endTime: '17:00',
        title: 'Desvendando o universo da cybersegurança',
        subtitle: '',
      },
      {
        startTime: '17:00',
        endTime: '18:00',
        title: 'Inteligência Artificial e Multimodalidade',
        subtitle: ''
      }, 
      {
        startTime: '18:00',
        endTime: '19:00',
        title: 'INTERVALO',
        subtitle: ''
      }, 
      {
        startTime: '19:00',
        endTime: '23:00',
        title: 'MINICURSOS A',
        subtitle: ''
      }, 
    ],
    'QUARTA-FEIRA': [
      {
        startTime: '08:00',
        endTime: '09:00',
        title: 'ROADMAP DE CARREIRA',
        subtitle: 'Tempest',
      },
      {
        startTime: '09:00',
        endTime: '10:00',
        title: 'WORKSHOP TRACTIAN',
        subtitle: '',
      },
      {
        startTime: '10:00',
        endTime: '11:00',
        title: 'PALESTRA TEMPEST',
        subtitle: 'por Luckas Judocka',
      },
      {
        startTime: '11:00',
        endTime: '12:00',
        title: 'PALESTRA TRACTIAN',
        subtitle: '',
      },
      {
        startTime: '13:00',
        endTime: '14:00',
        title: 'INTERVALO',
        subtitle: '',
      },
      {
        startTime: '14:00',
        endTime: '15:00',
        title: 'PALESTRAS',
        subtitle: 'QITECH',
      },
      {
        startTime: '15:00',
        endTime: '16:00',
        title: 'PALESTRAS',
        subtitle: 'PÓS-GRADUAÇÃO',
      },
      {
        startTime: '16:00',
        endTime: '16:30',
        title: 'COFFEE BREAK',
        subtitle: '',
      },
      {
        startTime: '16:30',
        endTime: '17:30',
        title: 'PALESTRA VISAGIO',
        subtitle: '',
      },
      {
        startTime: '17:30',
        endTime: '18:30',
        title: 'PALESTRA MAGALU CLOUD',
        subtitle: '',
      },
      {
        startTime: '18:30',
        endTime: '19:00',
        title: 'INTERVALO',
        subtitle: '',
      },
      {
        startTime: '19:00',
        endTime: '22:30',
        title: 'M@U CHALLENGE',
        subtitle: '',
      },
    ],
    'QUINTA-FEIRA': [
      {
        startTime: '08:00',
        endTime: '09:00',
        title: 'Java e IA Generativa',
        subtitle: '',
      },
      {
        startTime: '09:00',
        endTime: '10:00',
        title: 'O papel de UX Security',
        subtitle: 'Em cibersegurança',
      },
      {
        startTime: '10:00',
        endTime: '10:30',
        title: 'COFFEE BREAK',
        subtitle: '',
      },
      {
        startTime: '10:30',
        endTime: '11:30',
        title: 'POMBO:',
        subtitle: 'A história dos heróis ocultos da Comp UFSCAR',
      },
      {
        startTime: '11:30',
        endTime: '12:30',
        title: 'DESENVOLVIMENTO E FINAÇAS',
        subtitle: 'Onde está a item',
      },
      {
        startTime: '12:30',
        endTime: '14:00',
        title: 'INTERVALO',
        subtitle: '',
      },
      {
        startTime: '14:00',
        endTime: '18:00',
        title: 'MINUCURSOS B',
        subtitle: '',
      },
      {
        startTime: '18:00',
        endTime: '19:00',
        title: 'INTERVALO',
        subtitle: '',
      },
      {
        startTime: '19:00',
        endTime: '05:00',
        title: 'HACKATHON MAGALU CLOUD',
        subtitle: '',
        extend: true,
      },
    ],
    'SEXTA-FEIRA': [
      {
        startTime: '08:00',
        endTime: '12:00',
        title: 'MINICURSOS C',
        subtitle: '',
      },
      {
        startTime: '12:00',
        endTime: '14:00',
        title: 'INTERVALO',
        subtitle: '',
      },
      {
        startTime: '14:00',
        endTime: '15:00',
        title: 'PROGRAMAÇÃO FUNCIONAL:',
        subtitle: 'História e Padrões de Desenvolvimento',
      },
      {
        startTime: '15:00',
        endTime: '16:00',
        title: 'Escalabilidade: Uma Demonstração Prática',
        subtitle: '',
      },
      {
        startTime: '16:00',
        endTime: '16:30',
        title: 'COFFEE BREAK',
        subtitle: '',
      },
      {
        startTime: '16:30',
        endTime: '17:30',
        title: 'De átomos ao assembler',
        subtitle: '',
      },
      {
        startTime: '17:30',
        endTime: '18:30',
        title: 'FLASH TALKS',
        subtitle: '',
      },
      {
        startTime: '18:30',
        endTime: '19:00',
        title: 'INTERVALO',
        subtitle: '',
      },
      {
        startTime: '19:00',
        endTime: '20:00',
        title: 'PREMIAÇÕES E ENCERRAMENTO',
        subtitle: '',
      },
      {
        startTime: '20:00',
        endTime: '08:00',
        title: 'GAMENIGHT',
        subtitle: '',
      },
    ],
  };